In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("Dry_Bean.csv")
df

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0      28395    610.291       208.178117       173.888747      1.197191   
1      28734    638.018       200.524796       182.734419      1.097356   
2      29380    624.110       212.826130       175.931143      1.209713   
3      30008    645.884       210.557999       182.516516      1.153638   
4      30140    620.134       201.847882       190.279279      1.060798   
...      ...        ...              ...              ...           ...   
13606  42097    759.696       288.721612       185.944705      1.552728   
13607  42101    757.499       281.576392       190.713136      1.476439   
13608  42139    759.321       281.539928       191.187979      1.472582   
13609  42147    763.779       283.382636       190.275731      1.489326   
13610  42159    772.237       295.142741       182.204716      1.619841   

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0          0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1          0.411785       29172     191.272751  0.783968  0.984986   0.887034   
2          0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3          0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4          0.333680       30417     195.896503  0.773098  0.990893   0.984877   
...             ...         ...            ...       ...       ...        ...   
13606      0.765002       42508     231.515799  0.714574  0.990331   0.916603   
13607      0.735702       42494     231.526798  0.799943  0.990752   0.922015   
13608      0.734065       42569     231.631261  0.729932  0.989899   0.918424   
13609      0.741055       42667     231.653247  0.705389  0.987813   0.907906   
13610      0.786693       42600     231.686223  0.788962  0.989648   0.888380   

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  \
0         0.913358      0.007332      0.003147      0.834222      0.998724   
1         0.953861      0.006979      0.003564      0.909851      0.998430   
2         0.908774      0.007244      0.003048      0.825871      0.999066   
3         0.928329      0.007017      0.003215      0.861794      0.994199   
4         0.970516      0.006697      0.003665      0.941900      0.999166   
...            ...           ...           ...           ...           ...   
13606     0.801865      0.006858      0.001749      0.642988      0.998385   
13607     0.822252      0.006688      0.001886      0.676099      0.998219   
13608     0.822730      0.006681      0.001888      0.676884      0.996767   
13609     0.817457      0.006724      0.001852      0.668237      0.995222   
13610     0.784997      0.007001      0.001640      0.616221      0.998180   

          Class  
0         SEKER  
1         SEKER  
2         SEKER  
3         SEKER  
4         SEKER  
...         ...  
13606  DERMASON  
13607  DERMASON  
13608  DERMASON  
13609  DERMASON  
13610  DERMASON  

[13611 rows x 17 columns]

In [3]:
df.shape

(13611, 17)

# spliting data 

In [4]:
x=df.drop('Class',axis=1)

In [5]:
y=df['Class']

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=3)

In [7]:
x_train.shape

(8166, 16)

In [8]:
x_test.shape

(5445, 16)

# random forst

In [9]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
rf=RandomForestClassifier( n_estimators=100,criterion='gini')

In [21]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [29]:
ypred=rf.predict(x_test)
ypred

array(['BOMBAY', 'SIRA', 'SEKER', ..., 'HOROZ', 'CALI', 'BARBUNYA'],
      dtype=object)

In [23]:
x_test

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
3567  167321   1578.125       588.299273       368.170441      1.597899   
9646   49355    837.190       306.668192       205.813377      1.490030   
1649   43964    795.449       266.710262       210.168541      1.269030   
3932   59841    936.317       354.646935       217.641344      1.629502   
8225   42257    772.737       285.230673       189.547831      1.504795   
...      ...        ...              ...              ...           ...   
8212   42206    779.537       292.501733       184.238206      1.587628   
6040   49613    870.384       329.673575       196.451383      1.678143   
5832   47074    877.067       365.928067       166.188149      2.201890   
4487   72077   1063.400       414.832638       224.714311      1.846045   
2956   74925   1119.975       398.325952       240.481075      1.656371   

      Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
3567      0.779966      170889     461.562253  0.777333  0.979121   0.844263   
9646      0.741342       49989     250.680549  0.726054  0.987317   0.884897   
1649      0.615671       44557     236.593963  0.778841  0.986691   0.873137   
3932      0.789551       61068     276.028853  0.692965  0.979908   0.857754   
8225      0.747251       42749     231.955348  0.796340  0.988491   0.889293   
...            ...         ...            ...       ...       ...        ...   
8212      0.776700       42781     231.815332  0.758051  0.986559   0.872792   
6040      0.803061       51012     251.334903  0.642805  0.972575   0.822969   
5832      0.890923       47846     244.819277  0.605469  0.983865   0.768998   
4487      0.840573       73996     302.937760  0.759185  0.974066   0.800964   
2956      0.797189       76127     308.864813  0.753325  0.984211   0.750620   

      Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  
3567     0.784570      0.003516      0.000822      0.615551      0.983588  
9646     0.817433      0.006214      0.001711      0.668196      0.995632  
1649     0.887082      0.006067      0.002317      0.786915      0.998619  
3932     0.778320      0.005926      0.001342      0.605782      0.987123  
8225     0.813220      0.006750      0.001821      0.661327      0.995162  
...           ...           ...           ...           ...           ...  
8212     0.792526      0.006930      0.001687      0.628098      0.997186  
6040     0.762375      0.006645      0.001385      0.581216      0.975363  
5832     0.669037      0.007773      0.000961      0.447610      0.985588  
4487     0.730265      0.005755      0.001010      0.533287      0.984472  
2956     0.775407      0.005316      0.001186      0.601256      0.995904  

[5445 rows x 16 columns]

In [24]:
from sklearn.metrics import classification_report

In [25]:
print('cl_report',classification_report(y_test,ypred))

cl_report               precision    recall  f1-score   support

    BARBUNYA       0.94      0.92      0.93       535
      BOMBAY       1.00      1.00      1.00       208
        CALI       0.93      0.94      0.94       675
    DERMASON       0.90      0.93      0.91      1391
       HOROZ       0.95      0.94      0.95       759
       SEKER       0.95      0.94      0.94       796
        SIRA       0.89      0.87      0.88      1081

    accuracy                           0.92      5445
   macro avg       0.94      0.93      0.94      5445
weighted avg       0.92      0.92      0.92      5445



In [26]:
from sklearn.metrics import accuracy_score

In [30]:
print('accu_sco',accuracy_score(y_test,ypred)*100)

accu_sco 92.3783287419651


# adaboost_classifier

In [31]:
x_train.shape

(8166, 16)

In [32]:
x_test.shape

(5445, 16)

In [34]:
from sklearn.ensemble import AdaBoostClassifier

In [35]:
adc=AdaBoostClassifier()

In [36]:
adc.fit(x_train,y_train)

AdaBoostClassifier()

In [38]:
ypred=adc.predict(x_test)
ypred

array(['BARBUNYA', 'SIRA', 'SEKER', ..., 'HOROZ', 'CALI', 'CALI'],
      dtype=object)

In [39]:
x_test

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
3567  167321   1578.125       588.299273       368.170441      1.597899   
9646   49355    837.190       306.668192       205.813377      1.490030   
1649   43964    795.449       266.710262       210.168541      1.269030   
3932   59841    936.317       354.646935       217.641344      1.629502   
8225   42257    772.737       285.230673       189.547831      1.504795   
...      ...        ...              ...              ...           ...   
8212   42206    779.537       292.501733       184.238206      1.587628   
6040   49613    870.384       329.673575       196.451383      1.678143   
5832   47074    877.067       365.928067       166.188149      2.201890   
4487   72077   1063.400       414.832638       224.714311      1.846045   
2956   74925   1119.975       398.325952       240.481075      1.656371   

      Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
3567      0.779966      170889     461.562253  0.777333  0.979121   0.844263   
9646      0.741342       49989     250.680549  0.726054  0.987317   0.884897   
1649      0.615671       44557     236.593963  0.778841  0.986691   0.873137   
3932      0.789551       61068     276.028853  0.692965  0.979908   0.857754   
8225      0.747251       42749     231.955348  0.796340  0.988491   0.889293   
...            ...         ...            ...       ...       ...        ...   
8212      0.776700       42781     231.815332  0.758051  0.986559   0.872792   
6040      0.803061       51012     251.334903  0.642805  0.972575   0.822969   
5832      0.890923       47846     244.819277  0.605469  0.983865   0.768998   
4487      0.840573       73996     302.937760  0.759185  0.974066   0.800964   
2956      0.797189       76127     308.864813  0.753325  0.984211   0.750620   

      Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  
3567     0.784570      0.003516      0.000822      0.615551      0.983588  
9646     0.817433      0.006214      0.001711      0.668196      0.995632  
1649     0.887082      0.006067      0.002317      0.786915      0.998619  
3932     0.778320      0.005926      0.001342      0.605782      0.987123  
8225     0.813220      0.006750      0.001821      0.661327      0.995162  
...           ...           ...           ...           ...           ...  
8212     0.792526      0.006930      0.001687      0.628098      0.997186  
6040     0.762375      0.006645      0.001385      0.581216      0.975363  
5832     0.669037      0.007773      0.000961      0.447610      0.985588  
4487     0.730265      0.005755      0.001010      0.533287      0.984472  
2956     0.775407      0.005316      0.001186      0.601256      0.995904  

[5445 rows x 16 columns]

In [40]:
from sklearn.metrics import classification_report

In [42]:
print('classification report',classification_report(y_test,ypred))

classification report               precision    recall  f1-score   support

    BARBUNYA       0.00      0.00      0.00       535
      BOMBAY       0.00      0.00      0.00       208
        CALI       0.49      0.99      0.66       675
    DERMASON       0.64      0.95      0.76      1391
       HOROZ       0.99      0.57      0.73       759
       SEKER       0.91      0.21      0.35       796
        SIRA       0.72      0.77      0.75      1081

    accuracy                           0.63      5445
   macro avg       0.54      0.50      0.46      5445
weighted avg       0.64      0.63      0.58      5445



E:\python.py\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
E:\python.py\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
E:\python.py\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [43]:
from sklearn.metrics import accuracy_score

In [45]:
accuracy_score(y_test,ypred)*100

63.158861340679515

In [47]:
from sklearn.metrics import confusion_matrix

In [49]:
print('c.materix',confusion_matrix(y_test,ypred))

c.materix [[   0    0  444    0    0    1   90]
 [ 208    0    0    0    0    0    0]
 [   0    0  670    0    0    1    4]
 [   0    0    0 1327    0    0   64]
 [   0    0  213    8  436    0  102]
 [   0    0    0  566    0  170   60]
 [   0    0   37  188    6   14  836]]


# xg boost clf

In [60]:
import xgboost as xgb

ModuleNotFoundError: No module named 'xgboost'